# Домашнее задание "Линейная алгебра. Матрицы".

In [24]:
import pandas as pd
import numpy as np

## Задание 1

✅ Создайте матрицу 3х3, заполненную числами от 1 до 9

In [25]:
m = np.matrix([x for x in range(1,10)]).reshape(3,3)
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

✅ Прибавьте к ней матрицу с единицами на диагонале

In [26]:
m = m + np.eye(3,3)
m

matrix([[ 2.,  2.,  3.],
        [ 4.,  6.,  6.],
        [ 7.,  8., 10.]])

✅ Умножьте полученную матрицу на вектор (1, 2, 3)

In [27]:
v = np.array([1,2,3]) * m
v

matrix([[31., 38., 45.]])

✅ Вычислить транспонированную матрицу от полученной в результате прибавления матрицы

In [28]:
mT = m.T
mT

matrix([[ 2.,  4.,  7.],
        [ 2.,  6.,  8.],
        [ 3.,  6., 10.]])

✅ Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [29]:
np.linalg.inv(m)

matrix([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
        [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
        [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

## Задание 2

✅ Найдите собственные значения и собственные вектора матрицы

In [30]:
m = np.array([[2, 2],
              [1, 3]])
m

array([[2, 2],
       [1, 3]])

In [32]:
evalues, evectors = np.linalg.eig(m)
print('Собственные значения', evalues)
print('Собственные вектора',  evectors)

Собственные значения [1. 4.]
Собственные вектора [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


## Задание 3


✅ Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0. 
Матрица должна быть ненулевой и размерностью не менее 2!

In [65]:
np.linalg.det([
    [1,1],
    [1,2]
])

1.0